name: build-and-push

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**/README.md"
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  build-and-push:
    name: Build and push image to ghcr
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        image:
          - fedora
          - ubuntu
        include:
          - release: 42
            image: fedora
          - release: 24.04
            image: ubuntu
    env:
      IMAGE_NAME: ${{ matrix.image }}
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
      IMAGE_RELEASE: ${{ matrix.release }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.IMAGE_RELEASE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          build-args: |
            IMAGE_RELEASE=${{ env.IMAGE_RELEASE }}
          file: ./${{ env.IMAGE_NAME }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
